OPENAI_API_TYPE = "azure"
OPENAI_API_KEY = "92318a90857d4d9a9d8188e21bf7a867"
OPENAI_API_BASE = "https://cognitive-search-openai.openai.azure.com/"
OPENAI_API_VERSION = "2023-05-15"
GPT_ENGINE_NAME = "gpt-35-turbo"
EMBEDDING_ENGINE_NAME = "text-embedding-ada-002"
SEARCH_ENDPOINT = "https://bof-cognitive-search.search.windows.net/" #st.secrets["AZURE_SEARCH_ENDPOINT"]
SEARCH_KEY = "OvYaa8C2mFZ57UzcOtu03nsskpxS8OjPJspIr41As6AzSeAn5H2w"