OPENAI_API_TYPE = "test"
OPENAI_API_KEY = "test"
OPENAI_API_BASE = "test"
OPENAI_API_VERSION = "2023-05-15"
GPT_ENGINE_NAME = "gpt-35-turbo"
EMBEDDING_ENGINE_NAME = "text-embedding-ada-002"
SEARCH_ENDPOINT = "test"
SEARCH_KEY = "test"
